apiVersion: {{ include "common.capabilities.deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: {{ include "common.names.fullname" . }}-apiserver
  labels: {{- include "backend.labels.standard" . | nindent 4 }}
  {{- with .Values.apiserver.annotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: 1 #{{ .Values.apiserver.replicaCount }}
  {{- if .Values.apiserver.persistentVolume.enabled }}
  strategy:
    type: Recreate
  {{- end }}
  selector:
    matchLabels: {{- include "backend.labels.matchLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{- include "backend.labels.standard" . | nindent 8 }}
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets: {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- if .Values.apiserver.serviceAccount.create}}
      serviceAccountName: {{ include "common.names.fullname" . }}-apiserver
      {{- end }}
      securityContext: {{- toYaml .Values.apiserver.podSecurityContext | nindent 8 }}
      {{- with .Values.apiserver.initContainers }}
      initContainers: {{- toYaml . | nindent 6 }}
      {{- end }}
      containers:
      - name: {{ .Chart.Name }}-apiserver
        securityContext: {{- toYaml .Values.apiserver.securityContext | nindent 12 }}
        image: {{ include "apiserver.image" . }}
        imagePullPolicy: {{ .Values.apiserver.image.pullPolicy }}
        {{- with .Values.apiserver.resources }}
        resources: {{ . | toYaml | nindent 10 }}
        {{- end }}
        env:
        - name: SYSTEM_REQUIREMENT_CHECK_ENABLED
          value: "false"
        - name: ALPINE_DATA_DIRECTORY
          value: "/data"
        {{- if .Values.postgresql.enabled }}
        - name: ALPINE_DATABASE_MODE
          value: "external"
        - name: ALPINE_DATABASE_DRIVER
          value: "org.postgresql.Driver"
        - name: ALPINE_DATABASE_URL
          value: jdbc:postgresql://{{ .Release.Name }}-postgresql/{{ .Values.postgresql.auth.database }}
        - name: ALPINE_DATABASE_PASSWORD
          value: {{ .Values.postgresql.auth.password }}
          # valueFrom:
          #   secretKeyRef:
          #     name: {{ .Release.Name }}-postgresql
          #     key: postgresql-password
        - name: ALPINE_DATABASE_USERNAME
          value: {{ .Values.postgresql.auth.username }}
        {{- end }}
        {{- with .Values.apiserver.env }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        volumeMounts:
        - name: data
          mountPath: /data
        - name: tmp
          mountPath: /tmp
        ports:
        - name: api
          containerPort: 8080
          protocol: TCP
        {{- if .Values.apiserver.livenessProbe.enabled }}
        livenessProbe:
          httpGet:
            port: api
            path: {{ .Values.apiserver.livenessProbe.path }}
          initialDelaySeconds: {{ .Values.apiserver.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.apiserver.livenessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.apiserver.livenessProbe.timeoutSeconds }}
          successThreshold: {{ .Values.apiserver.livenessProbe.successThreshold }}
          failureThreshold: {{ .Values.apiserver.livenessProbe.failureThreshold }}
        {{- end }}
        {{- if .Values.apiserver.readinessProbe.enabled }}
        readinessProbe:
          httpGet:
            port: api
            path: {{ .Values.apiserver.readinessProbe.path }}
          initialDelaySeconds: {{ .Values.apiserver.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.apiserver.readinessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.apiserver.readinessProbe.timeoutSeconds }}
          successThreshold: {{ .Values.apiserver.readinessProbe.successThreshold }}
          failureThreshold: {{ .Values.apiserver.readinessProbe.failureThreshold }}
        {{- end }}
      {{- with .Values.apiserver.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.apiserver.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.apiserver.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      - name: tmp
        emptyDir: {}
      - name: data
        {{- if .Values.apiserver.persistentVolume.enabled }}
        persistentVolumeClaim:
          claimName: {{ if .Values.apiserver.persistentVolume.existingClaim }}{{ .Values.apiserver.persistentVolume.existingClaim }}{{- else }}{{ include "common.names.fullname" . }}-apiserver{{- end }}
        {{- else }}
        emptyDir:
        {{- if .Values.apiserver.emptyDir.sizeLimit }}
          sizeLimit: {{ .Values.apiserver.emptyDir.sizeLimit }}
        {{- else }}
          {}
        {{- end -}}
        {{- end }}