apiVersion: v2
name: dependency-track
version: 4.13.2
icon: https://raw.githubusercontent.com/DependencyTrack/branding/refs/heads/master/dt-logo-symbol-blue-background.png
type: application
appVersion: 4.13.2
description: |-
  A Helm chart to install dependencytrack with a postgres database backend. 
home: https://dependencytrack.org/
# sources:
#   - https://github.com/
dependencies:
- name: postgresql
  version: ~15.5
  repository: https://charts.bitnami.com/bitnami
  condition: postgresql.enabled
- name: common
  version: 2.x.x
  repository: https://charts.bitnami.com/bitnami